DELETE
FROM HT_KHAISINH
WHERE ID = 586604

CREATE TABLE TRACE
(
    ID INT,
    TIME_MODIFIED DATETIME
)
GO
SELECT *
FROM TRACE
GO
CREATE TRIGGER TRIGGER_MODIFIED ON HT_KHAISINH
AFTER DELETE, INSERT, UPDATE
AS
BEGIN
SET NOCOUNT ON
INSERT INTO TRACE(ID, TIME_MODIFIED) SELECT i.ID, GETDATE() FROM inserted as i 
UNION ALL SELECT ID, GETDATE() FROM deleted as d
END