# Generated by Django 4.0.3 on 2022-05-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Danhsachpdf',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Duongdanxuly',
        ),
        migrations.DeleteModel(
            name='Nguoidung',
        ),
        migrations.DeleteModel(
            name='Thongtinbienmuc',
        ),
        migrations.DeleteModel(
            name='Thongtinbienmuc2',
        ),
        migrations.DeleteModel(
            name='Thongtinbienmucna',
        ),
        migrations.DeleteModel(
            name='Vanban',
        ),
        migrations.DeleteModel(
            name='Vanbanna',
        ),
    ]
